---
# command arguments from dbimage-make.sh

ipAddrDib: "{{ lookup('env', 'DBIMAGE_IPADDR') }}"
dbName: "{{ lookup('env', 'DBIMAGE_DBNAME') }}"
# Given a Version.Release.Maintenance, trim it to V.R.  Users don't ask for Maintenance levels.
dbVersion: "{{ '.'.join(lookup('env', 'DBIMAGE_DBVERSION').split('.', 2)[:2]) | default('') }}"
pkg: "{{ lookup('env', 'DBIMAGE_PKG') }}"
pkgType: "{{ lookup('env', 'DBIMAGE_PKGTYPE') }}"
installScript: "{{ lookup('env', 'DBIMAGE_INSTALLSCRIPT') }}"
cloudUser: "{{ lookup('env', 'DBIMAGE_USER') }}"
gitUrl: "{{ lookup('env', 'DBIMAGE_GITURL') }}"
gitTag: "{{ lookup('env', 'DBIMAGE_GITTAG') }}"
baseDir: "{{ lookup('env', 'DBIMAGE_DIR') }}"
ipAddrController: "{{ lookup('env', 'DBIMAGE_CONTROLLER_IP') }}"
dibUser: "{{ lookup('env', 'DBIMAGE_DIBUSER') }}"
dbimageHome: "{{ lookup('env', 'DBIMAGE_HOME') }}"
communityEdition: "{{ lookup('env', 'DBIMAGE_COMMUNITY_EDITION') | bool }}"

# Environment variables set by the user directed at diskimage-builder

distroName: "{{ lookup('env', 'DISTRO_NAME') | default('') }}"
dibRelease: "{{ lookup('env', 'DIB_RELEASE') | default('') }}"
dibDebug: "{{ lookup('env', 'DIB_MYDEBUG') | default('') }}"

# Environment variables set by the user directed at Trove

imageSource: "{{ lookup('env', 'DBIMAGE_SOURCE') | default ('') }}"

# pip packages needed by dbimage-builder usually on controller

dbimage_apt_packages:
  - qemu-utils

dbimage_pip_packages:

# Apt packages needed by dibvm

dib_apt_packages:
  - git
  - kpartx
  - vlan
  - htop
  - aptitude
  - curl
  - build-essential
  - ntp
  - ntpdate
  - python-dev
  - python-pip
  - libssl-dev
  - libxml2-dev
  - libxslt-dev
  - pkg-config
  - libffi-dev
  - libpq-dev
  - libmysqlclient-dev
  - graphviz
  - libsqlite3-dev
  - gettext
  - screen
  - bridge-utils
  - unzip
  - grub2
  - qemu-utils

# pip packages needed by dibvm beyond dib requirements.txt

dib_pip_packages:

# versions for git cloned projects in dibvm

dib_version: 1.28.0
trove_version: stable/newton
trove_integration_version: 7.0.0

# dibvm install options

clean_environment: true

# Source locations in dbimage-builder

src_home: "{{ baseDir }}/dibvm/home"

src_trove: "{{ baseDir }}/etc/trove"

src_ssh: "{{ baseDir }}/etc/ssh"

src_dib_diffs:

src_trove_integration_diffs:
  - "{{ baseDir }}/diffs/trove/integration/15-reddwarf-dep.patch"
  - "{{ baseDir }}/diffs/trove/integration/trove-guestagent.patch"
  - "{{ baseDir }}/diffs/trove/integration/trove-mariadb.patch"
  - "{{ baseDir }}/diffs/trove/integration/trove-mysql.patch"
  - "{{ baseDir }}/diffs/trove/integration/trove-redis.patch"
  - "{{ baseDir }}/diffs/trove/integration/trove-postgresql.patch"

src_trove_guestagent_diffs:
  - "{{ baseDir }}/diffs/trove/guestagent/postgres-config.patch"
  - "{{ baseDir }}/diffs/trove/guestagent/postgres-fix-ctrl-template.patch"

src_trove_guestagent_debug_diffs:
  - "{{ baseDir }}/diffs/trove/guestagent-debug/debug-common.patch"
  - "{{ baseDir }}/diffs/trove/guestagent-debug/debug-postgres.patch"

# Target locations in dibvm

dib_home: "/home/{{ dibUser }}"

