---
# Copyright 2016 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Installation and setup of Trove
  hosts: trove_all
  user: root
  pre_tasks:
    - name: Use the lxc-openstack aa profile
      lxc_container:
        name: "{{ container_name }}"
        container_config:
          - "lxc.aa_profile=lxc-openstack"
      delegate_to: "{{ physical_host }}"
      when: not is_metal | bool
      register: container_config
      tags:
        - lxc-aa-profile

    - name: Wait for container ssh
      wait_for:
        port: "22"
        delay: "{{ ssh_delay }}"
        search_regex: "OpenSSH"
        host: "{{ ansible_ssh_host }}"
      delegate_to: "{{ physical_host }}"
      when: container_config is defined and container_config | changed
      register: ssh_wait_check
      until: ssh_wait_check | success
      retries: 3
      tags:
        - ssh-wait

    - name: Update apt sources
      apt:
        update_cache: yes
        cache_valid_time: 600
      register: apt_update
      until: apt_update|success
      retries: 5
      delay: 2
      tags:
        - trove-pkgs
        - trove-apt-pkgs

    - name: Install mysql apt packages
      apt:
        pkg: "{{ item }}"
        state: latest
      register: install_packages
      until: install_packages|success
      retries: 5
      delay: 2
      with_items: internal_db_pkgs
      tags:
        - trove-db-setup

    - name: Create DB for Trove
      mysql_db:
         login_user: "{{ galera_root_user }}"
         login_password: "{{ galera_root_password }}"
         login_host: "{{ trove_galera_address }}"
         name: "{{ trove_galera_database }}"
         state: "present"
      delegate_to: "{{ groups['galera_all'][0] }}"
      run_once: true
      tags:
         - trove-db-setup

    - name: Grant access to the DB for Trove
      mysql_user:
         login_user: "{{ galera_root_user }}"
         login_password: "{{ galera_root_password }}"
         login_host: "{{ trove_galera_address }}"
         name: "{{ trove_galera_user }}"
         password: "{{ trove_galera_password }}"
         host: "{{ item }}"
         state: "present"
         priv: "{{ trove_galera_database }}.*:ALL"
      with_items:
         - "localhost"
         - "%"
      delegate_to: "{{ groups['galera_all'][0] }}"
      run_once: true
      tags:
         - trove-db-setup

    - name: Ensure Rabbitmq vhost for Trove
      rabbitmq_vhost:
         name: "{{ trove_rabbitmq_vhost }}"
         state: "present"
      delegate_to: "{{ groups['rabbitmq_all'][0] }}"
      run_once: true
      tags:
         - trove-rabbitmq
         - trove-rabbitmq-vhost

    - name: Ensure rabbitmq user for Trove
      rabbitmq_user:
         user: "{{ trove_rabbitmq_userid }}"
         password: "{{ trove_rabbitmq_password }}"
         vhost: "{{ trove_rabbitmq_vhost }}"
         configure_priv: ".*"
         read_priv: ".*"
         write_priv: ".*"
         state: "present"
      delegate_to: "{{ groups['rabbitmq_all'][0] }}"
      run_once: true
      tags:
         - trove-rabbitmq
         - trove-rabbitmq-user

    - name: Sort the rabbitmq servers
      dist_sort:
         value_to_lookup: "{{ container_name }}"
         ref_list: "{{ groups['trove_all'] }}"
         src_list: "{{ rabbitmq_servers }}"
      register: servers
      tags:
         - trove-rabbitmq

    - name: Set rabbitmq servers
      set_fact:
         rabbitmq_servers: "{{ servers.sorted_list }}"
      tags:
         - trove-rabbitmq

  roles:
    - role: "openstack_openrc"
      tags: "trove-openstack-openrc"

    - role: "power_trove"
      tags: "power_trove role"
      trove_openstack_db_connection_string: "mysql+pymysql://{{ trove_galera_user }}:{{ trove_galera_password }}@{{ trove_galera_address }}/{{ trove_galera_database }}"
      trove_repo: https://git.openstack.org/openstack/trove.git
      trove_repo_branch: stable/mitaka
      trove_rabbitmq_port: "{{ rabbitmq_port }}"

  vars:
      is_metal: "{{ properties.is_metal|default(false) }}"
      trove_galera_address: "{{ internal_lb_vip_address }}"
      trove_rabbitmq_servers: "{{ rabbitmq_servers }}"
      trove_rabbitmq_use_ssl: "{{ rabbitmq_use_ssl }}"
      internal_db_pkgs:
          - python-mysqldb
