---
# Copyright 2016 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure the pre-req software on ppc64le compute host
  hosts: compute_all
  user: root

  tasks:
    - name: Install QEMU/Libvirt packages
      apt:
        pkg: "{{ item }}"
        force: yes
        state: present
      register: install_packages|success
      with_items:
        - qemu-system-ppc
        - libvirt-bin
      tags:
       - pkvm-install-libvirt

    - name: Disable SMT
      command: /usr/sbin/ppc64_cpu --smt=off
      tags:
       - pkvm-disable-smt

    - name: Upstart script to disable SMT
      copy:
        src: "files/smt.conf"
        dest: "/etc/init/smt.conf"
